### PR TITLE
Randomize signature updates within 2 hours

### PR DESCRIPTION
**Pull request by filippocarletti**
Updates should start from 2:32 (+120 seconds) to 4:32

### CODE REVIEW

**Comment by filippocarletti** [comment]
NethServer/dev#5649

**Comment by gsanchietti** [comment]
Why not moving the script under cron.daily which is already randomized?

**Comment by filippocarletti** [comment]
> Why not moving the script under cron.daily which is already randomized?

I don't know why it was fixed at 2:30.
I can't see problems in using cron.daily, apart from if we need/want to update more than once a day.

**Comment by gsanchietti** [comment]
Since we are not scheduling it more than once a day, please move it under cron.daily to reflect current conventions.

**Pull request merged**
